# Generated by Django 3.0.11 on 2020-12-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_updated',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
