# Generated by Django 3.0.11 on 2021-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210115_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
