# Generated by Django 3.0.11 on 2021-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_issue_material_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='totol_cost',
            field=models.FloatField(default=0),
        ),
    ]
