# Generated by Django 3.0.11 on 2021-01-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210107_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='factory_name',
        ),
    ]
