# Generated by Django 3.0.11 on 2021-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_receipt_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
