# Generated by Django 3.0.11 on 2021-01-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_receipt_totol_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='totol_cost',
            new_name='total_cost',
        ),
        migrations.AddField(
            model_name='factory',
            name='title',
            field=models.CharField(default='Rượu Hinh', max_length=200),
        ),
    ]
