# Generated by Django 3.0.11 on 2021-03-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Import',
        ),
    ]
