# Generated by Django 3.0.11 on 2021-03-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210324_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='Inventory',
        ),
    ]
