# Generated by Django 3.0.11 on 2021-03-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210324_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Import',
            new_name='Receipt',
        ),
    ]
