# Generated by Django 3.0.6 on 2020-09-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_available_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_on',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
