# Generated by Django 3.0.6 on 2020-09-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200904_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='name',
        ),
    ]
