# Generated by Django 3.0.11 on 2020-11-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumb',
        ),
    ]
